const BAD_REQUEST = 400;
const OK_STATUS = 200;
const CREATE = 201;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST,
  OK_STATUS,
  NOT_FOUND,
  CREATE,
  INTERNAL_SERVER_ERROR,
};
